services:
  dummy:
    container_name: dummy
    image: traefik/whoami
    command:
       - --port=80
       - --name=dummy
    networks:
      - no-internet
      - internet
networks:
  no-internet:
    driver: bridge
    internal: true
  internet:
    driver: bridge
    driver_opts:    # pass options to driver for network creation
      com.docker.network.bridge.host_binding_ipv4: 0.0.0.0